[2024-05-02T19:33:17.420-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T19:33:17.444-0300] {taskinstance.py:2063} INFO - Dependencies not met for <TaskInstance: a_primeira_DAG_v1.hello scheduled__2023-10-14T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-05-02T19:33:17.447-0300] {local_task_job_runner.py:163} INFO - Task is not able to be run
