[2024-05-03T21:14:29.775-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T21:14:29.800-0300] {taskinstance.py:2063} INFO - Dependencies not met for <TaskInstance: a_primeira_DAG_v2.hello scheduled__2024-03-11T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-05-03T21:14:29.802-0300] {local_task_job_runner.py:163} INFO - Task is not able to be run
